# Generated by Django 4.2.4 on 2023-09-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('working_mode', models.CharField(choices=[('T', 'Travail'), ('F', 'Férié'), ('CP', 'Congé Payé'), ('R', 'Récupération'), ('M', 'Maladie'), ('A', 'Absence')], max_length=2)),
                ('project_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
