# Generated by Django 4.2.4 on 2023-08-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='projet',
        ),
    ]
