# Generated by Django 4.2.4 on 2023-08-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realisation',
            old_name='date_creation',
            new_name='date_realisation',
        ),
    ]
