# Generated by Django 4.2.4 on 2023-08-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_remove_emplacement_name_user_remove_lists_name_user_and_more'),
        ('realisation', '0004_realisation_nature_realisation_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='nature',
        ),
        migrations.AddField(
            model_name='realisation',
            name='emplacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.emplacement'),
        ),
    ]
