# Generated by Django 4.2.4 on 2023-08-30 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0009_planification_nature_planification_projet'),
        ('realisation', '0005_remove_realisation_nature_realisation_emplacement'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='hr_est',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='planification.planification'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='realisations_tache', to='planification.planification'),
        ),
    ]
