# Generated by Django 4.2.4 on 2023-08-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0009_planification_nature_planification_projet'),
        ('realisation', '0006_realisation_hr_est_alter_realisation_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='hr_est',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='heures_estimee', to='planification.planification'),
        ),
    ]
