# Generated by Django 4.2.4 on 2023-08-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisation', '0007_alter_realisation_hr_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='livrable',
            field=models.FileField(max_length=10000, null=True, upload_to=''),
        ),
    ]
