# Generated by Django 4.2.4 on 2023-08-31 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisation', '0008_alter_realisation_livrable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='livrable',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
