# Generated by Django 4.2.4 on 2023-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realisation', '0009_alter_realisation_livrable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='livrable',
            field=models.FileField(upload_to='livrables/'),
        ),
    ]
