# Generated by Django 4.2.4 on 2023-09-01 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0010_alter_planification_nature'),
        ('lists', '0012_remove_emplacement_name_user_remove_lists_name_user_and_more'),
        ('realisation', '0010_alter_realisation_livrable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realisation',
            name='emplacement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.emplacement'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='hr_est',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heures_estimee', to='planification.planification'),
        ),
    ]
