# Generated by Django 4.2.4 on 2023-09-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realisation', '0012_alter_realisation_hr_est'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realisation',
            old_name='hr_est',
            new_name='hrs_est',
        ),
    ]
