# Generated by Django 4.2.4 on 2023-08-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_lists_my_objectif_lists_name_user'),
        ('objectif', '0002_objectif_delete_objectifs'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.lists'),
        ),
    ]
