# Generated by Django 4.2.4 on 2023-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0003_objectif_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='my_objectif',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
