# Generated by Django 4.2.4 on 2023-08-25 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_remove_lists_my_objectif_lists_name_user'),
        ('objectif', '0005_rename_my_objectif_objectif_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectif',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_nature', to='lists.lists'),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_projet', to='lists.lists'),
        ),
    ]
