# Generated by Django 4.2.4 on 2023-08-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_remove_emplacement_name_user_remove_lists_name_user_and_more'),
        ('objectif', '0006_objectif_nature_alter_objectif_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_nature', to='lists.nature'),
        ),
        migrations.AlterField(
            model_name='objectif',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objectifs_projet', to='lists.projet'),
        ),
    ]
