# Generated by Django 4.2.4 on 2023-08-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0007_alter_objectif_nature_alter_objectif_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='date_objectif',
            field=models.DateTimeField(null=True),
        ),
    ]
