# Generated by Django 4.2.4 on 2023-09-01 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_remove_emplacement_name_user_remove_lists_name_user_and_more'),
        ('objectif', '0008_alter_objectif_date_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objectifs_projet', to='lists.projet'),
        ),
    ]
