# Generated by Django 4.2.4 on 2023-09-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0011_alter_objectif_date_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectif',
            name='date_objectif',
            field=models.DateTimeField(null=True),
        ),
    ]
