# Generated by Django 4.2.4 on 2023-09-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_realiser', models.IntegerField()),
                ('task_non_realiser', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_objectives', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField()),
            ],
        ),
    ]
