# Generated by Django 4.2.4 on 2023-09-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_objectivestats_user_taskstats_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='task_non_realiser',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='objectivestats',
            name='total_objectives',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectstats',
            name='total_projects',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskstats',
            name='total_tasks',
            field=models.IntegerField(null=True),
        ),
    ]
