# Generated by Django 4.2.4 on 2023-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboard_task_non_realiser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='task_realiser',
            field=models.IntegerField(null=True),
        ),
    ]
