# Generated by Django 4.2.4 on 2023-09-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dashboard_task_realiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='total_task_count',
            field=models.IntegerField(null=True),
        ),
    ]
