# Generated by Django 4.2.4 on 2023-08-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objrctif', models.CharField(max_length=10000, null=True)),
                ('tache', models.CharField(max_length=10000, null=True)),
                ('hr_est', models.FloatField(max_length=10000, null=True)),
                ('livrable', models.CharField(max_length=10000, null=True)),
                ('date_tache', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
