# Generated by Django 4.2.4 on 2023-08-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planification',
            old_name='objrctif',
            new_name='my_objrctif',
        ),
    ]
