# Generated by Django 4.2.4 on 2023-08-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0002_objectif_delete_objectifs'),
        ('planification', '0002_rename_objrctif_planification_my_objrctif'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='planification',
    #         name='my_objectif',
    #         field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectif.objectif'),
    #     ),
    # ]
