# Generated by Django 4.2.4 on 2023-08-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0004_alter_objectif_my_objectif'),
        ('planification', '0005_remove_planification_my_objectif'),
    ]

    operations = [
        migrations.AddField(
            model_name='planification',
            name='my_objectif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectif.objectif'),
        ),
    ]
