# Generated by Django 4.2.4 on 2023-08-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0006_planification_my_objectif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planification',
            old_name='my_objectif',
            new_name='obj',
        ),
    ]
