# Generated by Django 4.2.4 on 2023-08-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0005_rename_my_objectif_objectif_obj'),
        ('planification', '0007_rename_my_objectif_planification_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planification',
            name='obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='objectif.objectif'),
        ),
    ]
