# Generated by Django 4.2.4 on 2023-08-30 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_remove_emplacement_name_user_remove_lists_name_user_and_more'),
        ('planification', '0008_alter_planification_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='planification',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.nature'),
        ),
        migrations.AddField(
            model_name='planification',
            name='projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.projet'),
        ),
    ]
