# Generated by Django 4.2.4 on 2023-09-01 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0012_remove_emplacement_name_user_remove_lists_name_user_and_more'),
        ('planification', '0009_planification_nature_planification_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planification',
            name='nature',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.nature'),
        ),
    ]
