# Generated by Django 4.2.4 on 2023-09-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planification', '0010_alter_planification_nature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planification',
            old_name='hr_est',
            new_name='hrs_est',
        ),
    ]
