# Generated by Django 4.2.4 on 2023-08-21 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.CharField(max_length=200, null=True)),
                ('nature', models.CharField(max_length=200, null=True)),
                ('emplacement', models.CharField(choices=[('siege', 'siege'), ('chantier', 'chantier')], max_length=200, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
