# Generated by Django 4.2.4 on 2023-08-21 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectif', '0002_objectif_delete_objectifs'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='my_objectif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='objectif.objectif'),
        ),
    ]
