# Generated by Django 4.2.4 on 2023-08-21 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_login_projet'),
        ('lists', '0002_lists_my_objectif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='my_objectif',
        ),
        migrations.AddField(
            model_name='lists',
            name='name_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.login'),
        ),
    ]
