# Generated by Django 4.2.4 on 2023-08-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_emplacement_nature_projet_alter_lists_emplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='emplacement',
            field=models.CharField(choices=[('siege', 'siege'), ('chantier', 'chantier')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lists',
            name='nature',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lists',
            name='projet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Emplacement',
        ),
        migrations.DeleteModel(
            name='Nature',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
