# Generated by Django 4.2.4 on 2023-08-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_login_projet'),
        ('lists', '0007_alter_lists_emplacement_alter_lists_nature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='name_user',
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.CharField(max_length=200, null=True)),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.login')),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=200, null=True)),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.login')),
            ],
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplacement', models.CharField(choices=[('siege', 'siege'), ('chantier', 'chantier')], max_length=200, null=True)),
                ('name_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.login')),
            ],
        ),
    ]
