# Generated by Django 4.2.4 on 2023-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0010_remove_projet_name_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='projet',
            field=models.CharField(max_length=200),
        ),
    ]
