# Generated by Django 4.2.4 on 2023-08-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0011_alter_projet_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emplacement',
            name='name_user',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='name_user',
        ),
        migrations.RemoveField(
            model_name='nature',
            name='name_user',
        ),
    ]
