# Generated by Django 4.2.4 on 2023-09-02 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0014_alter_emplacement_user_alter_nature_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
