# Generated by Django 4.2.4 on 2023-09-06 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0016_lists_all_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='All_projet',
        ),
        migrations.AddField(
            model_name='projet',
            name='All_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='totalOfProjectFilters', to='lists.projet'),
        ),
    ]
