# Generated by Django 4.2.4 on 2023-09-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0017_remove_lists_all_projet_projet_all_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='All_projet',
        ),
    ]
